name: "dotnet-publish"
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  dotnet-publish:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.test.outcome }}
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-dotnet@master
        with:
          dotnet-version: 8.0.x    

      - id: commonProps
        uses: juliangruber/read-file-action@v1
        with:
          path: ./common.props

      - id: getVersion
        uses: AsasInnab/regex-action@v1
        with:
          regex_pattern: '(?<=>)[^<>]+(?=</Version>)'
          regex_flags: 'gim'
          search_string: '${{ steps.commonProps.outputs.content }}'

      - id: nuget
        shell: pwsh
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/fs-tw/index.json -u fs-tw -p ${{ secrets.PERSONAL_TOKEN }}  --store-password-in-clear-text --name "github"
        continue-on-error: true

      - run: dotnet restore
        continue-on-error: false

      - run: dotnet build -c Release
        continue-on-error: false

      - run: dotnet test -c Release --no-restore --no-build
        continue-on-error: false

      - run: dotnet pack -c Release --no-build --property PackageOutputPath=${{ github.workspace }}/nugetPackages/
        continue-on-error: false

      - run: |
          cd ${{ github.workspace }}/nugetPackages
          shopt -s extglob
          rm -f !(Further.*)
          rm -f !(*.${{ steps.getVersion.outputs.first_match }}.nupkg)
          rm -f *.Blazor.Host.*
          rm -f *.Blazor.Server.Host.*
          rm -f *.Host.Shared.*
          rm -f *.HttpApi.Host.*
          rm -f *.IdentityServer.*
          rm -f *.AuthServer.*
          rm -f *.Web.Host.*
          rm -f *.Web.Unified.*
          rm -f *.HttpApi.Client.ConsoleTestApp.*
          rm -f *.Tests.*
          rm -f *.TestBase.*
          ls

      - uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
        with:
          nupkg-path:  '${{ github.workspace }}/nugetPackages/*.nupkg'
          repo-owner:  'fs-tw'
          gh-user:  'fs-tw'
          token: ${{ secrets.PERSONAL_TOKEN }}
          skip-duplicate: true

      - uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: ${{ steps.getVersion.outputs.first_match }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}         

      - if: ${{ steps.checkTag.outputs.exists == 'false' }}
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }} 
          tag: ${{ steps.getVersion.outputs.first_match }}            

  notify-end:
    runs-on: ubuntu-latest
    needs: [dotnet-publish]
    steps:
      - uses: louis70109/line-notify-action@master
        if : ${{ needs.dotnet-publish.outputs.outcome != 'success' }}
        with:
          token: r79j54p2crlTmuQChPt2grEhNYnI5351Hpk1J9idGZJ
          message: |

            ${{ github.repository}} : dotnet-publish
            Actor: ${{ github.actor }}
            PASS : ${{ github.repository}} dotnet-publish fail

      - uses: louis70109/line-notify-action@master
        if : ${{ needs.dotnet-publish.outputs.outcome == 'success' }}
        with:
          token: r79j54p2crlTmuQChPt2grEhNYnI5351Hpk1J9idGZJ
          message: |

            ${{ github.repository}} : dotnet-publish
            Actor: ${{ github.actor }}
            PASS : ${{ github.repository}} dotnet-publish success
